import asyncio
import datetime
from unittest import mock

from tran_jersey.app import init_app
from tran_jersey.njtransit import NjTransitClient


def return_future(result):
    f = asyncio.Future()
    f.set_result(result)
    return f


INVALID_NJTRANSIT_RECORD = {'BANNERMSGS': None,
                            'ITEMS': {'ITEM': [{'BACKCOLOR': '#009CDB',
                                                'CONNECTING_TRAIN_ID': '',
                                                'DESTINATION': 'New York -SEC &#9992',
                                                'FORECOLOR': 'white',
                                                'GPSLATITUDE': '40.408637',
                                                'GPSLONGITUDE': '-74.150195',
                                                'GPSTIME': datetime.datetime(2019, 12, 20, 22, 59,
                                                                             20),
                                                'INLINEMSG': '',
                                                'ITEM_INDEX': '0',
                                                'LAST_MODIFIED': datetime.datetime(2019, 12, 20, 22,
                                                                                   59, 27),
                                                'LINE': 'North Jersey Coast Line',
                                                'LINEABBREVIATION': 'NJCL',
                                                'SCHED_DEP_DATE': datetime.datetime(2019, 12, 20,
                                                                                    23, 2, 45),
                                                'SEC_LATE': '203',
                                                'SHADOWCOLOR': 'black',
                                                'STATION_POSITION': '1',
                                                'STATUS': 'in 6 Min',
                                                'STOPS': {'STOP': [{'DEPARTED': 'YES',
                                                                    'NAME': 'Long Branch',
                                                                    'STOP_STATUS': 'OnTime',
                                                                    'TIME': datetime.datetime(2019,
                                                                                              12,
                                                                                              20,
                                                                                              22,
                                                                                              37,
                                                                                              40)},
                                                                   {'DEPARTED': 'YES',
                                                                    'NAME': 'Little Silver',
                                                                    'STOP_STATUS': 'OnTime',
                                                                    'TIME': datetime.datetime(2019,
                                                                                              12,
                                                                                              20,
                                                                                              22,
                                                                                              45,
                                                                                              42)},
                                                                   {'DEPARTED': 'YES',
                                                                    'NAME': 'Red Bank',
                                                                    'STOP_STATUS': 'OnTime',
                                                                    'TIME': datetime.datetime(2019,
                                                                                              12,
                                                                                              20,
                                                                                              22,
                                                                                              50,
                                                                                              25)},
                                                                   {'DEPARTED': 'YES',
                                                                    'NAME': 'Middletown NJ',
                                                                    'STOP_STATUS': 'OnTime',
                                                                    'TIME': datetime.datetime(2019,
                                                                                              12,
                                                                                              20,
                                                                                              22,
                                                                                              56,
                                                                                              20)},
                                                                   {'DEPARTED': 'NO',
                                                                    'NAME': 'Hazlet',
                                                                    'STOP_STATUS': 'OnTime',
                                                                    'TIME': datetime.datetime(2019,
                                                                                              12,
                                                                                              20,
                                                                                              23, 1,
                                                                                              37)},
                                                                   {'DEPARTED': 'NO',
                                                                    'NAME': 'Aberdeen-Matawan',
                                                                    'STOP_STATUS': 'OnTime',
                                                                    'TIME': datetime.datetime(2019,
                                                                                              12,
                                                                                              20,
                                                                                              23, 5,
                                                                                              23)},
                                                                   {'DEPARTED': 'NO',
                                                                    'NAME': 'South Amboy',
                                                                    'STOP_STATUS': 'OnTime',
                                                                    'TIME': datetime.datetime(2019,
                                                                                              12,
                                                                                              20,
                                                                                              23,
                                                                                              14,
                                                                                              26)},
                                                                   {'DEPARTED': 'NO',
                                                                    'NAME': 'Perth Amboy',
                                                                    'STOP_STATUS': 'OnTime',
                                                                    'TIME': datetime.datetime(2019,
                                                                                              12,
                                                                                              20,
                                                                                              23,
                                                                                              18,
                                                                                              55)},
                                                                   {'DEPARTED': 'NO',
                                                                    'NAME': 'Woodbridge',
                                                                    'STOP_STATUS': 'OnTime',
                                                                    'TIME': datetime.datetime(2019,
                                                                                              12,
                                                                                              20,
                                                                                              23,
                                                                                              24,
                                                                                              7)},
                                                                   {'DEPARTED': 'NO',
                                                                    'NAME': 'Newark Airport',
                                                                    'STOP_STATUS': 'OnTime',
                                                                    'TIME': datetime.datetime(2019,
                                                                                              12,
                                                                                              20,
                                                                                              23,
                                                                                              39,
                                                                                              49)},
                                                                   {'DEPARTED': 'NO',
                                                                    'NAME': 'Newark Penn Station',
                                                                    'STOP_STATUS': 'OnTime',
                                                                    'TIME': datetime.datetime(2019,
                                                                                              12,
                                                                                              20,
                                                                                              23,
                                                                                              45,
                                                                                              19)},
                                                                   {'DEPARTED': 'NO',
                                                                    'NAME': 'Secaucus Upper Lvl',
                                                                    'STOP_STATUS': 'OnTime',
                                                                    'TIME': datetime.datetime(2019,
                                                                                              12,
                                                                                              20,
                                                                                              23,
                                                                                              55,
                                                                                              4)},
                                                                   {'DEPARTED': 'NO',
                                                                    'NAME': 'New York Penn Station',
                                                                    'STOP_STATUS': 'OnTime',
                                                                    'TIME': datetime.datetime(2019,
                                                                                              12,
                                                                                              21, 0,
                                                                                              8,
                                                                                              4)}]},
                                                'TRACK': '2',
                                                'TRAIN_ID': '3270'}
                                               ]}}

VALID_NJTRANSIT_RECORD = {'BANNERMSGS': None,
                          'ITEMS': {'ITEM': [{'BACKCOLOR': '#009CDB',
                                              'CONNECTING_TRAIN_ID': '',
                                              'DESTINATION': 'Long Branch',
                                              'FORECOLOR': 'white',
                                              'GPSLATITUDE': '40.533027',
                                              'GPSLONGITUDE': '-74.267892',
                                              'GPSTIME': datetime.datetime(2019, 12, 20, 22, 59,
                                                                           50),
                                              'INLINEMSG': '',
                                              'ITEM_INDEX': '1',
                                              'LAST_MODIFIED': datetime.datetime(2019, 12, 20, 22,
                                                                                 59, 53),
                                              'LINE': 'North Jersey Coast Line',
                                              'LINEABBREVIATION': 'NJCL',
                                              'SCHED_DEP_DATE': datetime.datetime(2019, 12, 20, 23,
                                                                                  17),
                                              'SEC_LATE': '0',
                                              'SHADOWCOLOR': 'black',
                                              'STATION_POSITION': '1',
                                              'STATUS': 'in 17 Min',
                                              'STOPS': {'STOP': [{'DEPARTED': 'YES',
                                                                  'NAME': 'Hoboken',
                                                                  'STOP_STATUS': 'OnTime',
                                                                  'TIME': datetime.datetime(2019,
                                                                                            12, 20,
                                                                                            22,
                                                                                            16)},
                                                                 {'DEPARTED': 'YES',
                                                                  'NAME': 'Newark Penn Station',
                                                                  'STOP_STATUS': 'OnTime',
                                                                  'TIME': datetime.datetime(2019,
                                                                                            12, 20,
                                                                                            22, 39,
                                                                                            47)},
                                                                 {'DEPARTED': 'NO',
                                                                  'NAME': 'South Amboy',
                                                                  'STOP_STATUS': 'OnTime',
                                                                  'TIME': datetime.datetime(2019,
                                                                                            12, 20,
                                                                                            23, 6,
                                                                                            15)},
                                                                 {'DEPARTED': 'NO',
                                                                  'NAME': 'Aberdeen-Matawan',
                                                                  'STOP_STATUS': 'OnTime',
                                                                  'TIME': datetime.datetime(2019,
                                                                                            12, 20,
                                                                                            23, 15,
                                                                                            30)},
                                                                 {'DEPARTED': 'NO',
                                                                  'NAME': 'Hazlet',
                                                                  'STOP_STATUS': 'OnTime',
                                                                  'TIME': datetime.datetime(2019,
                                                                                            12, 20,
                                                                                            23,
                                                                                            20)},
                                                                 {'DEPARTED': 'NO',
                                                                  'NAME': 'Middletown NJ',
                                                                  'STOP_STATUS': 'OnTime',
                                                                  'TIME': datetime.datetime(2019,
                                                                                            12, 20,
                                                                                            23, 26,
                                                                                            30)},
                                                                 {'DEPARTED': 'NO',
                                                                  'NAME': 'Red Bank',
                                                                  'STOP_STATUS': 'OnTime',
                                                                  'TIME': datetime.datetime(2019,
                                                                                            12, 20,
                                                                                            23,
                                                                                            33)},
                                                                 {'DEPARTED': 'NO',
                                                                  'NAME': 'Little Silver',
                                                                  'STOP_STATUS': 'OnTime',
                                                                  'TIME': datetime.datetime(2019,
                                                                                            12, 20,
                                                                                            23, 37,
                                                                                            15)},
                                                                 {'DEPARTED': 'NO',
                                                                  'NAME': 'Long Branch',
                                                                  'STOP_STATUS': 'OnTime',
                                                                  'TIME': datetime.datetime(2019,
                                                                                            12, 20,
                                                                                            23, 49,
                                                                                            30)}]},
                                              'TRACK': '1',
                                              'TRAIN_ID': '2609'}
                                             ]}}


class TestTransitOptions:

    async def test_get_transit_options_nodata(self, loop, aiohttp_client):

        with mock.patch.object(NjTransitClient, 'get_schedule',
                               return_value=return_future(INVALID_NJTRANSIT_RECORD)):
            app = await init_app()
            client = await aiohttp_client(app)
            resp = await client.get('/transit/schedule?origin=Aberdeen-Matawan&destination=Hazlet')
            assert resp.status == 200
            payload = await resp.json()
            assert len(payload["schedule"]) == 0

    async def test_get_transit_options(self, loop, aiohttp_client):

        with mock.patch.object(NjTransitClient, 'get_schedule',
                               return_value=return_future(VALID_NJTRANSIT_RECORD)):
            app = await init_app()
            client = await aiohttp_client(app)
            resp = await client.get('/transit/schedule?origin=Aberdeen-Matawan&destination=Hazlet')
            assert resp.status == 200
            payload = await resp.json()
            assert len(payload["schedule"]) > 0
